name: honey_cli
description: Command line utilities for honey
version: 0.0.2
homepage: https://honey.dev
repository: https://github.com/leisim/honey

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_tools:
    sdk: flutter
  honey_core: ^0.0.2
  honey_parser: ^0.0.2
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0
  collection: ^1.15.0
  glob: ^2.0.1
  args: ^2.2.0
  synchronized: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  freezed: ^1.0.0
  json_serializable: ^6.0.0

dependency_overrides:
  analyzer: ^2.7.0
  _fe_analyzer_shared: ^30.0.0
  freezed_annotation: ^1.0.0
  freezed: ^1.0.0
  honey_core: 
    path: ../honey_core
  honey_parser:
    path: ../honey_parser

executables:
  honey: honey
