name: honey_cli
description: CLI tools for the Honey Test framwork.
version: 0.1.1
homepage: https://honey.dev
repository: https://github.com/clickup/honey

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  args: ^2.3.1
  glob: ^2.1.0
  honey: ^0.1.1
  synchronized: ^3.0.0+3

dev_dependencies:
  very_good_analysis: ^3.1.0

executables:
  honey: honey
